stages:
  - deploy_production

deploy_production:
  stage: deploy_production
  tags:
    - ai-test-by-shell
  script:
    - source /root/.bashrc && cd /home/build/ml_platform_web/docker && git pull && ./build.sh
    - cd /home/build/ml_platform_deploy && docker-compose down && docker-compose up -d && echo "try visit: http://10.1.192.120:8016/"
  only:
    - master

